version: '3.9'

x-common_config: &common_config
  working_dir: /project/
  stop_signal: SIGKILL
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

services:
  tldrizer:
    <<: *common_config
    build: 
      context: .
      dockerfile: dockerfile
    image: tldrizer
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - .:/tldrizer
      - ./cache:/root/.cache/huggingface/hub/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/tldrizer:/tmp/tldrizer
